-- Admin-managed master data for dropdown option sets.
create table fas_master_options (
  id uuid primary key default gen_random_uuid(),
  set_key text not null,
  value text not null,
  label text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (set_key, value),
  check (char_length(value) between 1 and 80),
  check (char_length(label) between 1 and 120),
  check (set_key in ('countries', 'calling_codes', 'buyer_types', 'seller_types', 'incoterms'))
);
create index fas_master_options_set_idx on fas_master_options (set_key, sort_order, value);

create trigger fas_master_options_updated before update on fas_master_options
  for each row execute function set_updated_at();

insert into fas_master_options (set_key, value, label, sort_order) values
  ('countries', 'IN', 'India', 0),
  ('countries', 'AE', 'United Arab Emirates', 1),
  ('countries', 'US', 'United States', 2),
  ('countries', 'GB', 'United Kingdom', 3),
  ('countries', 'SG', 'Singapore', 4),
  ('countries', 'MY', 'Malaysia', 5),
  ('countries', 'SA', 'Saudi Arabia', 6),
  ('countries', 'QA', 'Qatar', 7),
  ('countries', 'OM', 'Oman', 8),
  ('countries', 'BH', 'Bahrain', 9),
  ('countries', 'KW', 'Kuwait', 10),
  ('countries', 'LK', 'Sri Lanka', 11),
  ('countries', 'BD', 'Bangladesh', 12),
  ('countries', 'NP', 'Nepal', 13),
  ('countries', 'MV', 'Maldives', 14),
  ('countries', 'ID', 'Indonesia', 15),
  ('countries', 'TH', 'Thailand', 16),
  ('countries', 'VN', 'Vietnam', 17),
  ('countries', 'AU', 'Australia', 18),
  ('countries', 'CA', 'Canada', 19),
  ('countries', 'DE', 'Germany', 20),
  ('countries', 'FR', 'France', 21),
  ('countries', 'NL', 'Netherlands', 22),
  ('countries', 'IT', 'Italy', 23),
  ('countries', 'ES', 'Spain', 24),
  ('countries', 'ZA', 'South Africa', 25),
  ('countries', 'KE', 'Kenya', 26),
  ('countries', 'TZ', 'Tanzania', 27),
  ('calling_codes', '+91', 'India (+91)', 0),
  ('calling_codes', '+971', 'United Arab Emirates (+971)', 1),
  ('calling_codes', '+1', 'United States / Canada (+1)', 2),
  ('calling_codes', '+44', 'United Kingdom (+44)', 3),
  ('calling_codes', '+65', 'Singapore (+65)', 4),
  ('calling_codes', '+60', 'Malaysia (+60)', 5),
  ('calling_codes', '+966', 'Saudi Arabia (+966)', 6),
  ('calling_codes', '+974', 'Qatar (+974)', 7),
  ('calling_codes', '+968', 'Oman (+968)', 8),
  ('calling_codes', '+973', 'Bahrain (+973)', 9),
  ('calling_codes', '+965', 'Kuwait (+965)', 10),
  ('buyer_types', 'Importer', 'Importer', 0),
  ('buyer_types', 'Exporter seeking supply', 'Exporter seeking supply', 1),
  ('buyer_types', 'Distributor', 'Distributor', 2),
  ('buyer_types', 'Wholesaler', 'Wholesaler', 3),
  ('buyer_types', 'Restaurant or hotel', 'Restaurant or hotel', 4),
  ('buyer_types', 'Supermarket', 'Supermarket', 5),
  ('buyer_types', 'Food manufacturer', 'Food manufacturer', 6),
  ('buyer_types', 'Seafood processor', 'Seafood processor', 7),
  ('buyer_types', 'Spice processor', 'Spice processor', 8),
  ('buyer_types', 'Private-label company', 'Private-label company', 9),
  ('buyer_types', 'Institutional buyer', 'Institutional buyer', 10),
  ('buyer_types', 'Trading company', 'Trading company', 11),
  ('buyer_types', 'Other', 'Other', 12),
  ('seller_types', 'Farmer', 'Farmer', 0),
  ('seller_types', 'Fish farmer', 'Fish farmer', 1),
  ('seller_types', 'Fishermen group', 'Fishermen group', 2),
  ('seller_types', 'Aquaculture farm', 'Aquaculture farm', 3),
  ('seller_types', 'Farmer organisation', 'Farmer organisation', 4),
  ('seller_types', 'Aggregator', 'Aggregator', 5),
  ('seller_types', 'Processor', 'Processor', 6),
  ('seller_types', 'Packer', 'Packer', 7),
  ('seller_types', 'Cold-storage operator', 'Cold-storage operator', 8),
  ('seller_types', 'Wholesaler', 'Wholesaler', 9),
  ('seller_types', 'Licensed exporter', 'Licensed exporter', 10),
  ('seller_types', 'Trading company', 'Trading company', 11),
  ('seller_types', 'Other', 'Other', 12),
  ('incoterms', 'EXW', 'EXW', 0),
  ('incoterms', 'FCA', 'FCA', 1),
  ('incoterms', 'FOB', 'FOB', 2),
  ('incoterms', 'CFR', 'CFR', 3),
  ('incoterms', 'CIF', 'CIF', 4),
  ('incoterms', 'DAP', 'DAP', 5),
  ('incoterms', 'DDP', 'DDP', 6),
  ('incoterms', 'Not decided', 'Not decided', 7);
